version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 
 
     # build image
     - run: |         
         docker info
         docker build -t netcoreapi-sample -f Dockerfile .
     # deploy the image
     - run: |         
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag netcoreapi-sample registry.heroku.com/$HEROKU_APP_NAME/web
         docker push registry.heroku.com/$HEROKU_APP_NAME/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $HEROKU_APP_NAME